### ISSUE TITLE
i got this error while deploy on vercel

### ISSUE THREAD

**Issue by razordouble7** [itbruno/linksforall#3]
![carbon](https://user-images.githubusercontent.com/104490528/177692725-4e850996-7c73-42ab-97b5-3549ac175b27.png)

**Comment by itbruno** [comment]
Hey @razordouble7 
Looks a issue with node version, can you try to run again with node `14.x` at Vercel settings?

You can change at Vercel dashboard in:
- **Your Project > Settings > General > Node.js Version**
