### ISSUE TITLE
Unable to change profile picture

### ISSUE THREAD

**Issue by zefazen** [itbruno/linksforall#9]
How do I change my profile picture? I've tried repeatedly but the picture still doesn't appear. Surprisingly, it's your profile picture that appears successfully. Please help

<img src="https://github.com/itbruno/linksforall/assets/152702949/0e6ee8c6-7c12-4e66-8d93-28787ac5002d" alt="Cuplikan Layar_2024-05-17_19-41-05" width="400" height="210">

**file**: linker/src/lib/user.json

```json
{
  "fullname": "Multimedia Smabara",
  "website": "https://multimediaa.github.io",
  "role": "Berhenti Bermimpi, Mulailah Beraksi",
  "bio": "Salah satu ekstrakurikuler di SMA Negeri 1 Baturraden",
  "image": "https://avatars.githubusercontent.com/u/152702949?v=4",

  "socialLinks": {
    "github": "https://github.com/multimediaa",
    "instagram": "https://www.instagram.com/multimedia_smabara",
    "youtube": "https://www.youtube.com/@multimediasmabara7785"
  }
}
```

**Repository**: https://github.com/Etrazc/linker
**Url**: https://multimediaa.vercel.app

**Comment by itbruno** [comment]
Hi @Etrazc , thanks for share this point.

This happens cause we have a `remotePatterns` config setting up to `avatars3.githubusercontent.com` host and your image is on `avatars.githubusercontent.com` host.

You can update the hostname adding the current image hostname or a wildcard.
At your [next.config.js](https://github.com/Etrazc/linker/blob/main/next.config.js) file, try to update the code for this

```ts
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com' // or '*' to accept any hostname
      }
    ]
  }
};

module.exports = nextConfig;
```


I also will create a PR with this fix.
